In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

### What is Pandas?

Pandas is a Python library used for data manipulation and analysis.

Think of Pandas as a tool that helps you work with data in the form of tables, similar to Excel.
We need to:

read the dataset
inspect the data
remove unwanted columns
handle missing values
select features
select target
modify categorical data

Pandas helps with all of these.

### train_test_split
This comes from Scikit-learn.

-What does it do?

It divides your dataset into:

Training data + Testing data

For example, suppose you have 1000 records.

You might use:

80% → training
20% → testing

### StandardScaler

StandardScaler is used for feature scaling
Why do we need scaling?

Imagine your dataset contains:

Age       Salary
22        25000
25        35000
30        50000

Look at the scales:

Age     → 22, 25, 30
Salary  → 25000, 35000, 50000

Salary has much larger numerical values.

Some ML algorithms can be affected by this difference in scale.

So we transform the features into a similar scale.

### fit() vs transform() vs fit_transform()

This is very important for interviews and ML.


fit()

The scaler learns the statistics from your data.
learn the unique categeories

For example:

scaler.fit(X_train)

It calculates things like:

mean
standard deviation

But it doesn't transform the data yet.


transform()

Uses the learned mean and standard deviation to transform the data.

X_train_scaled = scaler.transform(X_train)

fit_transform()

Does both:

X_train_scaled = scaler.fit_transform(X_train)


Very important rule

For training data:

X_train_scaled = scaler.fit_transform(X_train)

For testing data:

X_test_scaled = scaler.transform(X_test)


Why?

Because the scaler should learn the mean and standard deviation only from training data.

Otherwise, information from the test data leaks into the training process.

This is called data leakage.

### LabelEncoder

Machine learning algorithms generally work with numerical values, but datasets often contain text.

For example:

Gender
------
Male
Female
Female
Male

We can convert them into numbers:

Male    → 1
Female  → 0

That's where LabelEncoder can be used.

When should you use LabelEncoder?

It's mainly designed for encoding target labels.

For example:

Purchased
---------
Yes
No
Yes
No

You can convert:

Yes → 1
No  → 0

However, for input categorical features, LabelEncoder can sometimes introduce an artificial ordering.

For example:

Ahmedabad → 0
Delhi     → 1
Mumbai    → 2

This could incorrectly suggest:

Mumbai > Delhi > Ahmedabad
There isn't actually such an order.

For categorical input features, methods such as OneHotEncoder are often more appropriate


### pickle
pickle is a Python module used to save Python objects to a file and load them later.
imagine you trained:

model

and also created:

scaler

You don't want to retrain everything every time your application starts.

So you can save them.

In [2]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## Useful Pandas functions
df.head()

Shows first 5 rows.

df.tail()

Shows last 5 rows.

df.shape

Returns:

(1000, 5)

Meaning:

1000 rows
5 columns
df.info()

Shows data types and missing values.

df.describe()

Shows statistical information.

In [3]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
## Onehot encode 'Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()  ##data[['Geography']] this return a data frame
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
## Save the encoders and sscaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
## DiVide the dataset into indepent and dependent features
X=data.drop('Exited',axis=1) ##Drop the column named Exited
y=data['Exited']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

Here:

Exited

is what we want the ML model to predict.

For example:

Exited = 1 → Customer left
Exited = 0 → Customer stayed

So Exited is called the:

Dependent variable
Target variable
Output
Label

Why axis=1?

Pandas uses:

axis=0 → rows
axis=1 → columns

X → Inputs
y → Output


Why do we separate X and y?

Because during training we tell the model:

Here are the inputs → X
Here are the correct answers → y

### Split data into training and testing
                 DATA
                   ↓
        ┌──────────┴──────────┐
        ↓                     ↓
    Training               Testing
      80%                    20%    

      For example, if you have 10,000 rows:

Training → 8,000 rows
Testing  → 2,000 rows

### Why do we split the data?

Because we want to know whether our model can work on unseen data.

X_train

Training features
y_train

Correct answers corresponding to X_train.

X_test

Testing features.

Used to make predictions after training.

y_test

Actual answers for the test data.

Used to evaluate the model.


What does random_state=42 mean?

The splitting process is random.

Without random_state, you might get a different split each time.

For example:

Run 1 → rows 1,5,7,... → training
Run 2 → different rows → training


Setting:

random_state=42

makes the random split reproducible.

So whenever you run the code again, you'll get the same split.

42 itself isn't special. You could use:

random_state=10


Why do we NOT use fit_transform() on X_test?

You correctly wrote:

X_test = scaler.transform(X_test)

instead of:

X_test = scaler.fit_transform(X_test)

This is very important.

The scaler should learn the mean and standard deviation only from the training data.

So:

X_train
   ↓
fit()
   ↓
Learn mean + std
   ↓
transform X_train

Then:

X_test
   ↓
Use SAME mean + std
   ↓
transform X_test


--Why not fit on X_test?

If you do:

X_test = scaler.fit_transform(X_test)

the scaler learns information from the test data.

That means information from your test set has influenced your preprocessing.

This can cause data leakage.

The correct approach is:

X_train = scaler.fit_transform(X_train)


X_test = scaler.transform(X_test)
Remember this rule:

Training data → fit_transform()
Testing data → transform()

This rule is extremely important in ML.


                 ORIGINAL DATA
                      │
                      ↓
              ┌───────────────┐
              │   Separate    │
              │    X and y    │
              └───────────────┘
                  ↓       ↓
                  X       y
                  │       │
                  ↓       ↓
            train_test_split
                  │
          ┌───────┴────────┐
          ↓                ↓
       Training          Testing
          │                │
     X_train,y_train   X_test,y_test
          │                │
          ↓                ↓
     fit_transform()    transform()
          │                │
          ↓                ↓
     Scaled training   Scaled testing
          │                │
          └───────┬────────┘
                  ↓
              ML MODEL
                  ↓
               predict
                  ↓
              Evaluation

In [13]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [14]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [15]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

### ANN Implementation

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

WARNING:tensorflow:From f:\Udmey\Ann_Classification_Project1\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

### Tenserflow
What is TensorFlow?

TensorFlow is an open-source machine learning/deep learning framework developed by Google.

It is used to build and train:

ANN
CNN
RNN
LSTM
Transformers
Deep learning models


### Keras
What is Keras?

Keras is a high-level deep learning API integrated with TensorFlow.

It makes building neural networks much easier.

Instead of manually implementing:

neurons
weights
biases
forward propagation
backpropagation
gradient calculations

Keras provides ready-made components.


from tensorflow.keras.models import Sequential

--Sequential is used to create a neural network where layers are arranged one after another in a simple sequence
You can create it with:

model = Sequential() # you're creating the neural network model.

Then add layers:

model.add(Dense(10)) 
model.add(Dense(5))
model.add(Dense(1))


from tensorflow.keras.layers import Dense
--Dense represents a fully connected neural network layer.


from tensorflow.keras.callbacks import EarlyStopping
--EarlyStopping is a callback.

A callback allows you to perform an action during model training when a particular condition occurs.

Why do we need EarlyStopping?

Suppose you train your ANN for:

epochs=100

The model might improve initially:

Epoch 1  → validation loss = 0.50
Epoch 2  → validation loss = 0.45
Epoch 3  → validation loss = 0.40
...
Epoch 20 → validation loss = 0.30
Epoch 21 → validation loss = 0.31
Epoch 22 → validation loss = 0.33
Epoch 23 → validation loss = 0.35

The model stopped improving on validation data.

Continuing to train may cause overfitting.



from tensorflow.keras.callbacks import TensorBoard
--TensorBoard is a visualization and monitoring tool that comes with the TensorFlow ecosystem.

It allows you to visualize things like:

training loss
validation loss
training accuracy
validation accuracy
model graphs
training progress

Instead of only looking at:

Epoch 1
loss: 0.55
accuracy: 0.72

you can use TensorBoard to see graphs.

-What is an Epoch?

An epoch is one complete pass through the entire training dataset.

Suppose you have:

Training data = 1,000 rows

and you train your ANN with:

model.fit(X_train, y_train, epochs=10)

Then the model will see all 1,000 training rows 10 times
Epoch 1 → sees all 1,000 rows
Epoch 2 → sees all 1,000 rows
Epoch 3 → sees all 1,000 rows
...
Epoch 10 → sees all 1,000 rows

### 1 epoch = the model has gone through the entire training dataset once.

In [17]:
(X_train.shape[1],) ##Number of features/columns in X_train

(12,)

In [18]:
## Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected wwith input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='sigmoid')  ## output layer
]

)

WARNING:tensorflow:From f:\Udmey\Ann_Classification_Project1\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()  ##This loss function is commonly used for binary classification.
loss

### What is an optimizer?

An optimizer is responsible for updating the neural network's weights and biases during training.

Remember how an ANN learns:

Input
  ↓
Neural Network
  ↓
Prediction
  ↓
Loss
  ↓
Backpropagation
  ↓
Optimizer
  ↓
Update weights
  ↓
Better prediction

The optimizer decides how the weights should be changed to reduce the loss.


### What is Adam?
-Adam = Adaptive Moment Estimation
It is one of the most commonly used optimizers in deep learning.

Adam combines ideas related to:

Momentum
Adaptive learning rates

It automatically adjusts how much each parameter should change during training.

You don't need to calculate those updates manually.




What is learning_rate?

You have:

learning_rate=0.01

The learning rate controls how big the weight updates are.

Imagine the model has a weight:

Weight = 0.50

After calculating the error, the optimizer might decide:

Change weight

The learning rate influences how large that change is.

Learning rate too small

For example:

learning_rate=0.00001

The model may learn very slowly.

Weight
 ↓
tiny change
 ↓
tiny change
 ↓
tiny change

Training can take a very long time.

Learning rate too large

For example:

learning_rate=1

The updates could be too large.

The model might jump around instead of finding a good solution.

Good point
   ↓
jump too far
   ↓
jump other side
   ↓
jump again

Training may become unstable.

In [21]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [ ]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [23]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [24]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From f:\Udmey\Ann_Classification_Project1\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From f:\Udmey\Ann_Classification_Project1\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 5ms/step - loss: 0.3944 - accuracy: 0.8339 - val_loss: 0.3701 - val_accuracy: 0.8485
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3599 - accuracy: 0.8539 - val_loss: 0.3539 - val_accuracy: 0.8530
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3475 - accuracy: 0.8560 - val_loss: 0.3479 - val_accuracy: 0.8550
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3462 - accuracy: 0.8584 - val_loss: 0.3533 - val_accuracy: 0.8600
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3439 - accuracy: 0.8580 - val_loss: 0.3498 - val_accuracy: 0.8580
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8600 - val_loss: 0.3576 - val_accuracy: 0.8605
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3356 - accuracy: 0.8595 - val_loss: 0.3424 - val_accuracy: 0.8565
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3331 - accuracy: 0.8622 - val_loss: 0.3474 - val_accuracy: 0.8590
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3323 - accuracy: 0.8649 - val_loss: 0.3569 - val_accuracy: 0.8540
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3276 - accuracy: 0.8654 - val_loss: 0.3748 - val_accuracy: 0.8515
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3265 - accuracy: 0.8664 - val_loss: 0.3517 - val_accuracy: 0.8550
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3239 - accuracy: 0.8630 - val_loss: 0.3555 - val_accuracy: 0.8535
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3222 - accuracy: 0.8659 - val_loss: 0.3518 - val_accuracy: 0.8585
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3206 - accuracy: 0.8668 - val_loss: 0.3657 - val_accuracy: 0.8535
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3193 - accuracy: 0.8679 - val_loss: 0.3643 - val_accuracy: 0.8525
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3177 - accuracy: 0.8680 - val_loss: 0.3572 - val_accuracy: 0.8565
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3137 - accuracy: 0.8668 - val_loss: 0.3668 - val_accuracy: 0.8480

In [25]:
model.save('model.h5') ## Keras function used to save the model so you can load it later without training from scratch.

f:\Udmey\Ann_Classification_Project1\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [28]:
## Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [33]:
%tensorboard --logdir=logs

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\Udmey\Ann_Classification_Project1\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "F:\Udmey\Ann_Classification_Project1\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "F:\Udmey\Ann_Classification_Project1\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [ ]:
### Load the pickle file